# migrate-projects-execute.ps1
# Migrates Projects/ from flat {Account - Opp - Vendor} folders
# to account-centric {Account}/{Opp - Vendor}.md structure.
# Run migrate-projects-dry-run.ps1 first to review before executing.

$projectsRoot = "C:\Users\Chris\Documents\GitHub\dex\Projects"
$logFile      = "C:\Users\Chris\Documents\GitHub\dex\.scripts\migration-log.txt"

# ── special renames: old opp slug fragment → new filename (without .md) ──────
# Add entries here for any folder whose vendor/name needs correcting mid-migration
$renames = @{
    "CID - CNC Folder - MyersEPS - TRUMPF - Vendor"              = "CID - CNC Folder - Cidan Machinery"
    "TEC - 80â€™ Laser - Philly Shipyard - TECOi USA"            = "TEC - 80ft Laser - Philly Shipyard - TECOi USA"
    "TEC - 80' Laser - Philly Shipyard - TECOi USA"              = "TEC - 80ft Laser - Philly Shipyard - TECOi USA"
}

# ── helpers ───────────────────────────────────────────────────────────────────

function Get-FrontmatterValue($content, $key) {
    if ($content -match "(?m)^${key}:\s*(.+)$") { return $matches[1].Trim() } else { return $null }
}

function Get-MarkdownField($content, $label) {
    if ($content -match "\*\*${label}:\*\*\s*(.+)") { return $matches[1].Trim() } else { return $null }
}

function Get-AccountName($content) {
    $raw = Get-MarkdownField $content "Account"
    if (-not $raw) { return $null }
    if ($raw -match '\[\[.+\|(.+)\]\]') { return $matches[1].Trim() }
    if ($raw -match '\[\[(.+)\]\]')     { return $matches[1].Replace('_',' ').Trim() }
    return $raw
}

function Sanitize-Path($name) {
    # Fix Mojibake: UTF-8 curly quote read as Latin-1 (â€™ = right single quote ')
    $name = $name -replace 'â€™', "'"
    $name = $name -replace 'â€œ', '"'
    $name = $name -replace 'â€', '"'
    # Replace & with ' and ' — & is shell-problematic even though Windows allows it in filenames
    $name = $name -replace '&', ' and '
    $name = $name -replace '\s{2,}', ' '   # collapse double spaces from e.g. " & " → "  and  "
    # Strip remaining forbidden Windows filename chars
    $name = $name -replace '[\\/:*?"<>|]', '-'
    return $name.Trim('. ')
}

function Write-Log($msg) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$ts  $msg" | Tee-Object -FilePath $logFile -Append | Write-Host
}

function New-AccountHub($accountName, $oppFiles, $accountFolder) {
    $hubPath = Join-Path $accountFolder "$accountName.md"
    if (Test-Path $hubPath) { return }   # don't overwrite if it exists

    $rows = foreach ($f in ($oppFiles | Sort-Object Name)) {
        $c      = Get-Content $f.FullName -Raw -Encoding UTF8
        $stage  = Get-MarkdownField $c "Stage"
        $amount = Get-MarkdownField $c "Amount"
        $close  = Get-MarkdownField $c "Close Date"
        $vendor = Get-MarkdownField $c "Vendor"
        $opp    = $f.BaseName
        "| [[$opp]] | $stage | $amount | $close | $vendor |"
    }

    $totalOpps = $oppFiles.Count
    $content = @"
# $accountName

## Open Opportunities ($totalOpps)

| Opportunity | Stage | Amount | Close Date | Vendor |
|-------------|-------|--------|------------|--------|
$($rows -join "`n")

## Contacts

_See [[People/External]] for contact pages._

## Notes

-

## OneDrive Files

_Link account folder here once OneDrive integration is set up._

---
*Hub auto-generated by migration script $(Get-Date -Format 'yyyy-MM-dd'). Update as needed.*
"@
    Set-Content -Path $hubPath -Value $content -Encoding UTF8
    Write-Log "  HUB created: $accountName.md"
}

# ── main ──────────────────────────────────────────────────────────────────────

Write-Log "=== MIGRATION START ==="
"" | Out-File $logFile -Append

$folders = Get-ChildItem $projectsRoot -Directory | Sort-Object Name
$moved = 0; $skipped = 0; $errors = 0

foreach ($folder in $folders) {
    $mdFile = Get-ChildItem $folder.FullName -Filter "*.md" | Select-Object -First 1

    if (-not $mdFile) {
        Write-Log "SKIP (no .md): $($folder.Name)"
        $skipped++
        continue
    }

    $content     = Get-Content $mdFile.FullName -Raw -Encoding UTF8
    $accountRaw  = Get-AccountName $content

    if (-not $accountRaw) {
        Write-Log "SKIP (no account): $($folder.Name)"
        $skipped++
        continue
    }

    $accountClean  = Sanitize-Path $accountRaw
    $accountFolder = Join-Path $projectsRoot $accountClean

    # If this folder IS already the account folder, skip
    if ($folder.Name -eq $accountClean) {
        Write-Log "SKIP (already account folder): $($folder.Name)"
        $skipped++
        continue
    }

    # Derive opp slug: strip account prefix from folder name
    $escaped  = [regex]::Escape($accountRaw)
    $oppSlug  = ($folder.Name -replace "^${escaped}\s*-\s*", '').Trim()
    if (-not $oppSlug -or $oppSlug -eq $folder.Name) {
        # fallback: drop first segment
        $parts   = $folder.Name -split ' - ', 2
        $oppSlug = if ($parts.Count -gt 1) { $parts[1] } else { $folder.Name }
    }

    # Apply special renames
    foreach ($key in $renames.Keys) {
        if ($oppSlug -eq $key) {
            Write-Log "  RENAME: '$oppSlug' -> '$($renames[$key])'"
            $oppSlug = $renames[$key]
        }
    }

    $oppSlug  = Sanitize-Path $oppSlug
    $destDir  = $accountFolder
    $destFile = Join-Path $destDir "$oppSlug.md"

    # Create account folder if needed
    if (-not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Force -Path $destDir | Out-Null
        Write-Log "DIR created: $accountClean/"
    }

    # Check for collision
    if (Test-Path $destFile) {
        Write-Log "ERROR collision: '$destFile' already exists — skipping '$($folder.Name)'"
        $errors++
        continue
    }

    try {
        # Move the .md file
        Move-Item -Path $mdFile.FullName -Destination $destFile -ErrorAction Stop
        Write-Log "MOVED: $($folder.Name)/$($mdFile.Name) -> $accountClean/$oppSlug.md"

        # Move Quotes/ subfolder if present
        $quotesDir = Join-Path $folder.FullName "Quotes"
        if (Test-Path $quotesDir) {
            $destQuotes = Join-Path $destDir "Quotes_$oppSlug"
            Move-Item -Path $quotesDir -Destination $destQuotes -ErrorAction Stop
            Write-Log "  QUOTES moved: Quotes/ -> Quotes_$oppSlug/"
        }

        # Remove now-empty source folder
        if (-not (Get-ChildItem $folder.FullName)) {
            Remove-Item $folder.FullName -Force
        } else {
            Write-Log "  WARN: source folder not empty after move — leaving: $($folder.Name)"
        }

        $moved++
    }
    catch {
        Write-Log "ERROR: $($folder.Name) — $_"
        $errors++
    }
}

# ── generate account hub pages ───────────────────────────────────────────────

Write-Log ""
Write-Log "=== GENERATING ACCOUNT HUBS ==="

$accountDirs = Get-ChildItem $projectsRoot -Directory | Sort-Object Name
foreach ($dir in $accountDirs) {
    $oppFiles = Get-ChildItem $dir.FullName -Filter "*.md" | Where-Object { $_.BaseName -ne $dir.Name }
    if ($oppFiles.Count -gt 0) {
        New-AccountHub -accountName $dir.Name -oppFiles $oppFiles -accountFolder $dir.FullName
    }
}

# ── update pipeline sync skill to use new path convention ────────────────────

Write-Log ""
Write-Log "=== SUMMARY ==="
Write-Log "Moved:   $moved"
Write-Log "Skipped: $skipped"
Write-Log "Errors:  $errors"
Write-Log "Log:     $logFile"
Write-Log ""
Write-Log "Next steps:"
Write-Log "  1. Run migrate-projects-dry-run.ps1 again to confirm no flat folders remain"
Write-Log "  2. Update pipeline-sync skill to write to Projects/{Account}/{Opp}.md"
Write-Log "  3. Add same_buying_decision_as frontmatter where applicable (separate pass)"
Write-Log "=== DONE ==="
