#!/usr/bin/env python3
"""Generate the health promise register view and catch unregistered jobs.

Declared, not inferred: ``core/health/promises.py`` is the truth about what
each background job promises. This script is the inference side — it scans
the shipped tree for launchd job labels and fails when a job exists that
never registered a promise, so the register cannot silently fall behind the
code. With ``--write`` it renders ``docs/architecture/HEALTH-PROMISES.md``;
with ``--check`` it verifies the rendered view is current (CI drift gate).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "docs" / "architecture" / "HEALTH-PROMISES.md"
LABEL_PATTERN = re.compile(r"com\.dex\.[a-z0-9][a-z0-9-]*")
# Files that can introduce a launchd job.
CANDIDATE_SUFFIXES = (".plist", ".plist.template", ".sh")
# Labels that appear in code but are not shipped Dex background jobs.
IGNORED_LABELS: frozenset[str] = frozenset()


def _tracked_files() -> list[Path]:
    listing = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [REPO_ROOT / line for line in listing.stdout.splitlines() if line]


def discovered_labels() -> dict[str, list[str]]:
    """Scan shipped installers and templates for launchd job labels."""
    found: dict[str, list[str]] = {}
    for path in _tracked_files():
        if not path.name.endswith(CANDIDATE_SUFFIXES):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if "launchctl" not in text and not path.name.endswith((".plist", ".plist.template")):
            continue
        for label in LABEL_PATTERN.findall(text):
            if label in IGNORED_LABELS:
                continue
            found.setdefault(label, []).append(path.relative_to(REPO_ROOT).as_posix())
    return found


def render(promises, labels: dict[str, list[str]]) -> str:
    lines = [
        "# Health promises (generated)",
        "",
        "> Generated by `scripts/generate-health-promises.py --write`; do not edit.",
        "> The register itself lives in `core/health/promises.py`.",
        "",
        "Every recurring background job in Dex declares one promise: how often it",
        "succeeds, and where a *completed* run writes its receipt. Doctor's",
        "background-job freshness check — which Proactive Health snapshots and the",
        "in-session pulse reads — audits these receipts. A growing log is activity,",
        "not health; only receipts count, and activity-only entries say so.",
        "",
        "| Job | Promise | Cadence | Receipt | Proves |",
        "| --- | --- | --- | --- | --- |",
    ]
    for promise in promises:
        if promise.receipt_kind == "daemon":
            cadence = "continuous"
            proves = "liveness only (launchd)"
        else:
            hours = promise.cadence.total_seconds() / 3600
            cadence = f"every {hours:g} h"
            proves = "activity only" if promise.activity_only else "a completed run"
        receipt = f"`{promise.receipt_path}`"
        if promise.receipt_key:
            receipt += f" → `{promise.receipt_key}`"
        lines.append(
            f"| `{promise.id}` | {promise.label} | {cadence} | {receipt} | {proves} |"
        )
    lines.extend(
        [
            "",
            "## Where each job is declared",
            "",
        ]
    )
    for label in sorted(labels):
        sources = ", ".join(f"`{source}`" for source in sorted(set(labels[label])))
        lines.append(f"- `{label}`: {sources}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    sys.path.insert(0, str(REPO_ROOT))
    from core.health.promises import PROMISES

    labels = discovered_labels()
    registered = {promise.id for promise in PROMISES}
    unregistered = sorted(set(labels) - registered)
    if unregistered:
        for label in unregistered:
            sources = ", ".join(sorted(set(labels[label])))
            print(
                f"❌ background job {label} (declared in {sources}) has no entry in "
                "core/health/promises.py — register its success receipt so health "
                "checks can audit it",
                file=sys.stderr,
            )
        return 1
    orphaned = sorted(registered - set(labels))
    if orphaned:
        for label in orphaned:
            print(
                f"❌ promise {label} is registered but no shipped installer or "
                "template declares that job — remove the stale entry",
                file=sys.stderr,
            )
        return 1

    rendered = render(PROMISES, labels)
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"Wrote {OUTPUT}")
        return 0
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current != rendered:
        print(
            "❌ docs/architecture/HEALTH-PROMISES.md is stale; run "
            "python3 scripts/generate-health-promises.py --write and commit",
            file=sys.stderr,
        )
        return 1
    print("Health promise register is current and complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
